\c kaguya



INSERT INTO continents(id, name, code) VALUES(1, 'Africa', 'AF');
INSERT INTO continents(id, name, code) VALUES(2, 'Asia', 'AS');
INSERT INTO continents(id, name, code) VALUES(3, 'Europe', 'EU');
INSERT INTO continents(id, name, code) VALUES(4, 'North America', 'NA');
INSERT INTO continents(id, name, code) VALUES(5, 'Oceania', 'OC');
INSERT INTO continents(id, name, code) VALUES(6, 'South and Central America', 'SA');
INSERT INTO continents(id, name, code) VALUES(7, 'Commonwealth of Independent States and Associated Ethnic Groups', 'UR');

INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (1, '4', 'American', 'AM');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (2, '2', 'Arabian', 'AR');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (3,	6, 'Argentina', 'AR');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (4,	2, 'Armenian', 'AM');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (5,	2, 'Assyro-Babylonian', 'AB');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (6,	5, 'Australia', 'AU');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (7,	3, 'Austria', 'AS');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (8,	2, 'Babylon',	'BY');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (9,	3, 'Belgium',	'BE');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (10, 6, 'Brazil', 'BR');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (11, 3, 'Bulgaria', 'BU');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (12, 4, 'Canada', 'CA');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (13, 1, 'Canary Is.', 'CI');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (14, 7, 'Caucasus', 'CC');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (15, 2, 'China', 'CH');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (16, 6, 'Colombia', 'CO');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (17, 3, 'Czechoslovakia', 'CZ');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (18, 3, 'Denmark', 'DE');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (19, 1, 'Egypt', 'EG');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (20, 3, 'England', 'EN');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (21, 3, 'Finland', 'FI');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (22, 3, 'France', 'FR');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (23, 3, 'Germany', 'GE');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (24, 3, 'Great Britain', 'GB');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (25, 3, 'Greek', 'GR');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (26, 5, 'Hawaii', 'HA');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (27, 2, 'Hebrew', 'HE');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (28, 3, 'Hungary', 'HU');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (29, 2, 'India', 'IN');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (30, 2, 'Iraq', 'IQ');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (31, 3, 'Ireland', 'IR');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (32, 2, 'Israel', 'IS');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (33, 3, 'Italy', 'IT');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (34, 2, 'Japan', 'JA');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (35, 2, 'Jewish', 'JW');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (36, 3, 'Latin', 'LA');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (37, 4, 'Mexico', 'ME');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (38, 2, 'Mongolia', 'MO');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (39, 1, 'Morocco', 'MR');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (40, 3, 'Netherlands (Dutch)', 'DU');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (41, 5, 'New Zealand',	'NZ');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (42, 6, 'Nicaragua', 'NI');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (43, 3, 'Norway', 'NO');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (44, 2, 'Persian', 'PE');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (45, 3, 'Poland', 'PO');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (46, 3, 'Portugal', 'PG');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (47, 4, 'Pueblo', 'PU');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (48, 3, 'Roman', 'RM');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (49, 3, 'Romania (Rumania)', 'RO');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (50, 7, 'Russia', 'RU');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (51, 3, 'Scandinavian', 'SD');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (52, 3, 'Scotland', 'SC');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (53, 3, 'Slavic', 'SL');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (54, 1, 'South Africa', 'SA');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (55, 7, 'Soviet', 'SO');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (56, 3, 'Spain', 'SP');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (57, 3, 'Sweden', 'SW');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (58, 3, 'Switzerland', 'SZ');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (59, 2, 'Syria', 'SY');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (60, 2, 'Taiwan', 'TW');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (61, 2, 'Turkey', 'TU');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (62, 3, 'Ukraine', 'UK');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (63, 4, 'United States', 'US');
INSERT INTO ethnicitys(id, continent_id, name, code) VALUES (64, 3, 'Yugoslavia', 'YU');
