"""empty message

Revision ID: fff1438ce3e3
Revises: 
Create Date: 2021-01-17 14:14:00.932058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff1438ce3e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('pets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.alter_column('pets', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'pets', 'owners', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.alter_column('pets', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('pets', 'owner_id')
    op.alter_column('owners', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
